---
sidebar: sidebar
permalink: task-set-up-gcnv.html
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console
summary: The NetApp Console needs access to the Google Cloud NetApp Volumes API and the right permissions through a Google Cloud service account.
---

= Set up Google Cloud NetApp Volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Console needs the right permissions through a Google Cloud service account.

== Set up a service account

Complete the following tasks so that the NetApp Console can access your Google Cloud project:

* If you do not already have an existing service account, create a new one.
* Add the service account member to your project and assign it specific roles (permissions).
* Create and download a key pair for the service account that is used to authenticate to Google.

.Steps

. In the Google Cloud console, https://console.cloud.google.com/iam-admin/serviceaccounts[go to the Service accounts page^].

. Click *Select a project*, choose your project, and click *Open*.

. (Optional) To create a service account, do the following:
.. Click *Create service account*.

.. Enter the service account name (friendly display name) and description.
+
The Google Cloud Console generates a service account ID based on this name. Edit the ID if necessary - you cannot change the ID later.

.. To set access controls now, click *Create* and then *DONE* from the bottom of the page, and continue to the next step.

. From the _IAM page_ click *Add* and fill out the fields in the _Add Members_ page:

.. In the New Members field, enter the full service account ID.
+
For example: \user1-service-account-gcnv@project1.iam.gserviceaccount.com

.. Add one of these roles:
* _Google Cloud NetApp Volumes Admin_
OR
* _Google Cloud NetApp Volumes Viewer_

.. Click *Save*.

. Click the Service Account name, and then from the _Service account details_ page, click *Add key* and then *Create new key*.

. Select *JSON* as the key type and click *Create*.
+
By clicking *Create* your new public/private key pair is generated and downloaded to your system. It serves as the only copy of the private key. Store this file securely because it can be used to authenticate as your service account.

For detailed steps, refer to Google Cloud documentation:

* link:https://cloud.google.com/iam/docs/roles-permissions/netapp[Google Cloud NetApp Volumes roles and permissions^]
* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts[Creating and managing service accounts^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access[Granting, changing, and revoking access to resources^]
* link:https://cloud.google.com/iam/docs/creating-managing-service-account-keys[Creating and managing service account keys^]