---
sidebar: sidebar
permalink: task-set-up-gcnv.html
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console
summary: The NetApp Console needs access to the Google Cloud NetApp Volumes API and the right permissions through a Google Cloud service account.
---

= Set up Google Cloud NetApp Volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Console needs the right permissions through a Google Cloud service account.

Complete the following tasks so that the NetApp Console can access your Google Cloud project.

* If you do not already have an existing service account, create a new one.
* Grant access for impersonation.
* Grant the IAM role in the shared project.

== Set up a service account

. In the Google Cloud console, https://console.cloud.google.com/iam-admin/serviceaccounts[go to the Service accounts page^].

. Click *Select a project*, choose your project, and click *Open*.

. To create a service account, do the following:
.. Click *Create service account*.

.. Enter the service account name (friendly display name) and description.
+
The Google Cloud Console generates a service account ID based on this name. Edit the ID if necessary - you cannot change the ID later.

.. Click *Create and continue*.
.. From the Role list, select the *Google Cloud NetApp Volumes admin* or *Google Cloud NetApp viewer* role. 
+
To assign the *Google Cloud NetApp Volumes admin* role by using the Google Cloud CLI, run:
+
[source,bash]
----
gcloud projects add-iam-policy-binding PROJECT_ID \
  --member="serviceAccount:SERVICE_ACCOUNT_EMAIL" \
  --role="roles/netapp.admin"
----
.. Select *Continue*.
.. Grant impersonation access to this service account: credentials-sa@wf-production-netapp.iam.gserviceaccount.com. For details, see https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt[Create a self-signed JSON Web Token (JWT)^].
+
The service account owned by NetApp is used to request a short-lived access token that lets you act as that service account without needing access to its private key.
.. Click *DONE* at the bottom of the page, and continue to the next step.

== Shared VPC 

In each additional GCP project that will use the service account, do the following:

. In the _IAM page_, select the Shared VPC host project from the project dropdown menu. 
. Click *Add Principal*. 
. In the New principals field, enter the email address of your service account. 
. From the Select a role dropdown, choose the *Google Cloud NetApp Volumes admin* role.
. Click *Save*.

For detailed steps, refer to Google Cloud documentation:

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts[Creating and managing service accounts^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp[Google Cloud NetApp Volumes roles and permissions^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access[Granting, changing, and revoking access to resources^]

== Troubleshooting
If you encounter an error, the *iam.disableCrossProjectServiceAccountUsage* policy might be enforced. To fix this, do the following:

. In the Google Cloud console, go to the https://console.cloud.google.com/iam-admin/orgpolicies[Organization policies page^].
. Find the *Disable cross-project service account usage* policy and disable it.

.What's next?

link:task-add-roles.html[Assign Google Cloud NetApp Volumes roles].
